### ISSUE TITLE
Start strapi error mongoose schema

### ISSUE THREAD

**Issue by arnauddoub** [nicolashmln/strapi-plugin-oembed#1]
Hi, after following the configuration steps when I run "strapi develop" I get the following error message:

`error TypeError: Invalid schema configuration: `Oembed` is not a valid type at path `oembed`. See http://bit.ly/mongoose-schematypes for a list of valid schema types.`

Node.js version: 15.0.1
npm version: 7.0.3
Strapi version: 3.1.4

**Comment by nicolashmln** [comment]
Oh yeah, I only tried with a SQL database. If you try `"columnType": "text"` in your model, does it work?
If so I'll update the readme

**Comment by Zielgestalt** [comment]
"columnType": "text" works for postgres.

**Comment by RobinSJames** [comment]
> Oh yeah, I only tried with a SQL database. If you try `"columnType": "text"` in your model, does it work?

Getting this error when using MongoDB:

`error TypeError: Invalid schema configuration: "Text" is not a valid type at path "oembed".`

**Comment by RobinSJames** [comment]
If I use `"columnType: "string"`

The environment runs but terminal outputs the following:

```
(node:90880) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 unpipe listeners added to [WriteStream]. Use emitter.setMaxListeners() to increase limit
```

Then when trying to create a new article I get the following on screen:

<img width="1037" alt="Screenshot 2021-01-15 at 13 47 47" src="https://user-images.githubusercontent.com/43780747/104724072-d8ae0380-5738-11eb-9b17-b80c7c2cfdfb.png">

**Comment by nicolashmln** [comment]
@RobinSJames Which version of strapi do you run? Seems like the `columnType` is only supported from the 3.3.4 https://github.com/strapi/strapi/releases/tag/v3.3.4
But I don't know what are the values for MongoDB, maybe `String` with a capital `S`? If you could do some tests it will be helpful. Thank you

**Comment by shikharseth93** [comment]
"embeded_url":{
        "type": "oembed",
        "columnType": "string"
    }
    
  @arnauddoub  for me this worked, but I am stuck with different one
  while adding/updating any field in particular collection I am getting this message and not able to save

`{"error":{"contentType.attributes.embeded_url.type":["contentType.attributes.embeded_url.type must be one of the following values: media, string, text, richtext, json, enumeration, password, email, integer, biginteger, float, decimal, date, time, datetime, timestamp, boolean, uid, component, dynamiczone"],"contentType.attributes.embeded_url":["contentType.attributes.embeded_url field cannot have keys not specified in the object shape"]}}`

any idea? @nicolashmln

**Comment by gabyzenack** [comment]
something new
