### ISSUE TITLE
Strapi V4

### ISSUE THREAD

**Issue by violabg** [nicolashmln/strapi-plugin-oembed#10]
Any plan to port it to V4?

**Comment by nicolashmln** [comment]
Yes, that's in the pipe

**Comment by timur-kokdemir** [comment]
When do you plan to move the Strapi to the V4? Can we support this issue?

**Comment by nicolashmln** [comment]
All the work is done on the https://github.com/nicolashmln/strapi-plugin-oembed/tree/feat/strapi-v4 branch. At the moment the custom fields are not supported but it might have a workaround https://github.com/strapi/strapi/issues/12145#issuecomment-1008947142
I'll have a look later

cc @eminkokdemir @violabg

**Comment by ansmlc** [comment]
Hi @nicolashmln Any news on v4 integration?

**Comment by ernstjandevries1** [comment]
Awesome @nicolashmln any update on Strapi V4? Would love to use this

**Comment by GregorSondermeier** [comment]
With Strapi v4.4 now being released, custom fields are available :)

**Comment by mnzaki** [comment]
I have just created PR #12 adding the remaining glue bits. The new customFields API actually supports JSON data, but I did not change this in the plugin as it would break stuff (and seems unnecessary anyway, no harm in storing a text blob on the backend)

**Comment by nicolashmln** [comment]
@mnzaki thanks, I’ll publish that soon

**Comment by nicolashmln** [comment]
v1.0.0 is now compatible with strapi v4
