### ISSUE TITLE
Oembed This oembed is not available

### ISSUE THREAD

**Issue by SteveR92** [nicolashmln/strapi-plugin-oembed#2]
Hi,

I have installed oembed and inserted in to my model but get the following message in my views inside of the Strapi UI: **Oembed
This oembed is not available**

`  "attributes": {
    "Title": {
      "type": "string"
    },
    "Slug": {
      "type": "string"
    },
    "body": {
      "type": "richtext"
    },
    "oembed": {
      "type": "oembed",
      "columnType": "longtext"
    }
  }`

Many thanks,

Steve

**Comment by link82** [comment]
Hi Steve,
I faced the same issue,  because I forgot to execute `yarn build` before restarting the project.

You need to do the following:
```
yarn add strapi-plugin-oembed
update your model configuration
yarn build
yarn develop
```

Hope to help.
Davide

**Comment by nicolashmln** [comment]
Thank you for your message @link82. The same order as the README should work as well.
I close the issue

**Comment by fabiovaz** [comment]
but only works local, when i put on pgsql i cannot deploy
