### ISSUE TITLE
Vimeo domain-level privacy

### ISSUE THREAD

**Issue by Zielgestalt** [nicolashmln/strapi-plugin-oembed#4]
Feature request:

I want to embed several videos from vimeo that have domain-level privacy settings. For that I need to send a Referer header with the request (see [Vimeo Docs](https://developer.vimeo.com/api/oembed/videos#embedding-videos-with-domain-privacy)). I solved this by overriding the oembed service in my extensions folder.

``fetchedData = await axios.get(`https://vimeo.com/api/oembed.json?url=${encodeURIComponent(url)}`, {
              'headers': {
                'Referer': refererDomain
              }
            })``

I only need to embed the videos on one domain, so I hardcoded refererDomain as a constant.

Perhaps it is possible to find a general solution for this instead of overriding files and hardcoding domains. But I don't know where settings can be stored for a strapi plugin or how to add a field to the frontend.

And after all I'm not sure wether this setting should be a general setting for all vimeo videos or should it be possible to set it for every video.

Thanks

**Comment by nicolashmln** [comment]
A solution could be to have a textarea in the modal where you paste the url of the media. This textarea would be the options to pass to axios (as a JSON object to simplify). This textarea could be hidden under an "options" accordion because it won't be used by most of the people.
You'll have to paste the options every time you add a new video but I think it will be complicated to find a general solution without breaking the ease of use of adding media from other providers.  What do you think?

**Comment by Zielgestalt** [comment]
I agree, the ease of use of adding other providers is fantastic (I will add some more in future). But I think pasting the options every time could be very annoying for editors if it is always the same url. Could be a great feature if the url differs per video. But not ideal in my case.

Perhaps we can use axios options or axios Interceptors in a separated config file and import them to oembed.js. Per default the options are empty, so nothing has changed. But if I need them I can easily override the config file without overriding the main oembed.js.

e.g. in my case:

AxiosOption.js:

`module.exports = {
  headers: {'referer': 'https://www.example.com'}
 }`

In oembed.js:

`const options = require('./AxiosOptions');`

``fetchedData = await axios.get(`https://vimeo.com/api/oembed.json?url=${encodeURIComponent(url)}`, options).then(res => res.data);``

What do you think?

**Comment by nicolashmln** [comment]
(sorry I was away)
And this `AxiosOption.js` would only be applied to the fetch of vimeo?

I'm thinking of other use cases. For your specific use case it works well, but if a user wants to upload a video from vimeo. Sometimes with the header, sometimes without. He'll have to edit the code, which can be really annoying (having access to the server, rebuild strapi, etc.). And it can be two different persons who edit the code and who use it via the web UI.

**Comment by Zielgestalt** [comment]
Oh, I just learned that in Strapi you don't have to override a file, you can override a function, too. So there's no need for this feature. I can change that special function without losing updates on the other parts. So I think this is obsolete. Sorry, and thanks for your help!
