### ISSUE TITLE
Newbie question

### ISSUE THREAD

**Issue by mace07** [nicolashmln/strapi-plugin-oembed#5]
Hi folks - I'm totally new to strapi and (maybe more problematic) Next JS. I've got the plugin installed and if I go into the article [slug.js] on the backend and add {article.oembed} the page renders all the vimeo video JSON data. But I'm at a loss for how to parse that data to just present the video iframe instead of the json. Can anyone point me in the right direction? 

Thank you

**Comment by nicolashmln** [comment]
Look at the note in this section, you may find what you want https://github.com/nicolashmln/strapi-plugin-oembed#example-of-the-data-fetched 
I cannot give more details because it's not related to this plugin
