### ISSUE TITLE
Using GUID 

### ISSUE THREAD

**Issue by fabiovaz** [nicolashmln/strapi-plugin-oembed#9]
After manual installation of oembed, i can no longer use the "gui" interface to update component data.

![image](https://user-images.githubusercontent.com/1139471/143774884-daebd99b-c846-4188-a6f9-f28e1aa9135f.png)

**Comment by nicolashmln** [comment]
Do you have the error log?

**Comment by fabiovaz** [comment]
> Do you have the error log?

"contentType.attributes.oembed.type must be one of the following values: media, string, text, richtext, json, enumeration, password, email, integer, biginteger, float, decimal, date, time, datetime, timestamp, boolean, uid, component, dynamiczone"

```
cases.settings.json
"oembed": {
  "type": "oembed",
  "columnType": "text"
}
```

**Comment by nicolashmln** [comment]
I think that's a limitation of strapi. If you want to use the GUI you'll need to remove the oembed field. You can also add new fields manually.
